### PR TITLE
Solve Issue #30, DscResources.Common in submodule instead of GPRegistryPolicyDsc.Common

### LINKED ISSUE #30: [GPRegistryPolicyFileParser] Error with internationalization in GPRegistryPolicyFileParser submodule
#### Details of the scenario you tried and the problem that is occurring

I use GPRegistryPolicyDsc through CommonTasks, in french Windows Server 2016.
GPRegistryPolicyDsc contains submodule GPRegistryFileParser that used `Import-LocalizedData` cmdlet. In french system, this command tried to found `GPRegistryPolicyFileParser.strings.psd1` in `GPRegistryPolicyDsc\1.2.0\Modules\GPRegistryPolicyFileParser\fr-FR\` folder.

That generated an error in mof compilation. 
#### Suggested solution to the issue

There is only one language-specific data in the submodule. To avoid this problem, we could force the culture `en-US` in `Import-LocalizedData` with `UICulture` parameter.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running

```powershell
OsName               : Microsoft Windows Server 2016 Datacenter Evaluation
OsOperatingSystemSKU : 80
OsArchitecture       : 64 bits
WindowsBuildLabEx    : 14393.1944.amd64fre.rs1_release.171129-2100
OsLanguage           : fr-FR
OsMuiLanguages       : {fr-FR}

```
#### Version and build of PowerShell the target node is running
```powershell
Name                           Value
----                           -----
PSVersion                      5.1.14393.1944
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1944
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

#### Version of the DSC module that was used
```powershell
Name                Version Path
----                ------- ----
GPRegistryPolicyDsc 1.2.0   C:\Program Files\WindowsPowerShell\Modules\GPRegistryPolicyDsc\1.2.0\GPRegistryPolicyDsc.psd1
```

### PR DESCRIPTION
**Pull request by NicolasBn**
#### Pull Request (PR) description

With the submodule GPRegistryPolicyDsc.Common, there is an issue with internationalization.
To fix this, DscResources.Common module is used instead of GPRegistryPolicyDsc.Common.

#### This Pull Request (PR) fixes the following issues

- Fixes #30

#### Task list

- [Xed an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/gpregistrypolicydsc/31)

### CODE REVIEW

**Comment by FLeven** [comment]
Is still **not** working, it will reference the sub module path:

`$script:resourceHelperModulePath = Join-Path -Path $script:modulesFolderPath -ChildPath 'DscResource.Common'

Import-Module -Name $script:resourceHelperModulePath`

If i change the import to **"Import-Module -Name DscResource.Common"** everything works as expected.

**Comment by NicolasBn** [comment]
@FLeven Did you have DscResource.Common in folders referenced in `$env:PSModulePath`?

**Comment by FLeven** [comment]
@NicolasBn I installed the module from the gallery, if it is not a submodule anymore, I like to "see" and check it for updates from time to time. That's why "Import-Module -Name DscResource.Common" is working.

**Comment by johlju** [comment]
DscResource.Common should be bundled with the module GPRegistryPolicyDsc, that is the only way to avoid this module will break when breaking changes are introduced in DscResource.Common. The  correct version of the DscResource.Common that is required is pinned using the RequiredModules.psd1 when build this module. If a newer version should be used, a new version of the module GPRegistryPolicyDsc need to be build and deploy.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 7 of 12 files at r1, 1 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/gpregistrypolicydsc/31#-:-NiKksb5-ORxiq6yqYbA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NicolasBn)

**Pull request merged**
