### PR TITLE
Fix deploy to follow best practices and to remove .git folder

### LINKED ISSUE #3: Best practice is to add resources to module manifest
During deployment of v1.0.0 there was a warning outputted that there is a best practice to include the resources in the module manifest. I suggest we do that.

```
VERBOSE: Performing the operation "Publish-Module" on target "Version '1.0.0' of module 'GPRegistryPolicyDsc'".
This module 'C:\Users\appveyor\AppData\Local\Temp\1\805144811\GPRegistryPolicyDsc\GPRegistryPolicyDsc.psd1' has exported DscResources. As a best practice, include exported DSC resources in the module manifest file(.psd1). If your PowerShell version is higher than 5.0, run Update-ModuleManifest -DscResourcesToExport to update the manifest with ExportedDscResources field.
VERBOSE: Successfully published module 'GPRegistryPolicyDsc' to the module publish location 'https://www.powershellgallery.com/api/v2/package/'. Please allow few minutes for 'GPRegistryPolicyDsc' to show up in the search results.
Name                Version ModuleType ModuleBase                     
----                ------- ---------- ----------                     
GPRegistryPolicyDsc 1.0.0     Manifest C:\projects\gpregistrypolicydsc
Build success
```

### PR DESCRIPTION
**Pull request by jcwalker**
#### This Pull Request (PR) fixes the following issues
    Fixes #3

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing
      Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)
      and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/gpregistrypolicydsc/4)

### CODE REVIEW

**Comment by johlju** [comment]
Tag me when you feel this is ready :)

**Comment by jcwalker** [comment]
@johlju I think this is ready except for 1 thing.  The /branch build fails due to versioning.  I'm not exactly sure how we are handling that.

**Comment by johlju** [comment]
You should update the module manifest to `1.1.0`, and update the release notes in the manifest.

**Comment by johlju** [comment]
Maybe the version should be `1.0.1` since there are no functional changes in the module? Just CI pipeline updates.

**Pull request merged**
